//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlApiNfseGissInfra.NfseWSDL
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nfse.abrasf.org.br", ConfigurationName="XmlApiNfseGissInfra.NfseWSDL.nfse")]
    public interface nfse
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/nfse/ConsultarNfsePorRps", ReplyAction="http://nfse.abrasf.org.br/nfse/ConsultarNfsePorRpsResponse")]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorRps request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/nfse/ConsultarNfseServicoTomado", ReplyAction="http://nfse.abrasf.org.br/nfse/ConsultarNfseServicoTomadoResponse")]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoTomado request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/nfse/RecepcionarLoteRps", ReplyAction="http://nfse.abrasf.org.br/nfse/RecepcionarLoteRpsResponse")]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRps request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/nfse/RecepcionarLoteRpsSincrono", ReplyAction="http://nfse.abrasf.org.br/nfse/RecepcionarLoteRpsSincronoResponse")]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRpsSincrono request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/nfse/ConsultarNfseServicoPrestado", ReplyAction="http://nfse.abrasf.org.br/nfse/ConsultarNfseServicoPrestadoResponse")]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoPrestado request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/nfse/CancelarNfse", ReplyAction="http://nfse.abrasf.org.br/nfse/CancelarNfseResponse")]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.CancelarNfseResponse> CancelarNfseAsync(XmlApiNfseGissInfra.NfseWSDL.CancelarNfse request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/nfse/ConsultarLoteRps", ReplyAction="http://nfse.abrasf.org.br/nfse/ConsultarLoteRpsResponse")]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(XmlApiNfseGissInfra.NfseWSDL.ConsultarLoteRps request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/nfse/GerarNfse", ReplyAction="http://nfse.abrasf.org.br/nfse/GerarNfseResponse")]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.GerarNfseResponse> GerarNfseAsync(XmlApiNfseGissInfra.NfseWSDL.GerarNfse request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/nfse/SubstituirNfse", ReplyAction="http://nfse.abrasf.org.br/nfse/SubstituirNfseResponse")]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.SubstituirNfseResponse> SubstituirNfseAsync(XmlApiNfseGissInfra.NfseWSDL.SubstituirNfse request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/nfse/ConsultarNfsePorFaixa", ReplyAction="http://nfse.abrasf.org.br/nfse/ConsultarNfsePorFaixaResponse")]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorFaixa request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRps
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorRps()
        {
        }
        
        public ConsultarNfsePorRps(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorRpsResponse()
        {
        }
        
        public ConsultarNfsePorRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoTomadoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoTomado
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseServicoTomado()
        {
        }
        
        public ConsultarNfseServicoTomado(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoTomadoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoTomadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfseServicoTomadoResponse()
        {
        }
        
        public ConsultarNfseServicoTomadoResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRps
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRps()
        {
        }
        
        public RecepcionarLoteRps(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsResponse()
        {
        }
        
        public RecepcionarLoteRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsSincronoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsSincrono
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRpsSincrono()
        {
        }
        
        public RecepcionarLoteRpsSincrono(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsSincronoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsSincronoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsSincronoResponse()
        {
        }
        
        public RecepcionarLoteRpsSincronoResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoPrestadoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoPrestado
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseServicoPrestado()
        {
        }
        
        public ConsultarNfseServicoPrestado(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoPrestadoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoPrestadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfseServicoPrestadoResponse()
        {
        }
        
        public ConsultarNfseServicoPrestadoResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class CancelarNfse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public CancelarNfse()
        {
        }
        
        public CancelarNfse(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class CancelarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public CancelarNfseResponse()
        {
        }
        
        public CancelarNfseResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarLoteRps
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarLoteRps()
        {
        }
        
        public ConsultarLoteRps(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarLoteRpsResponse()
        {
        }
        
        public ConsultarLoteRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class GerarNfse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public GerarNfse()
        {
        }
        
        public GerarNfse(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class GerarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public GerarNfseResponse()
        {
        }
        
        public GerarNfseResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubstituirNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class SubstituirNfse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public SubstituirNfse()
        {
        }
        
        public SubstituirNfse(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubstituirNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class SubstituirNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public SubstituirNfseResponse()
        {
        }
        
        public SubstituirNfseResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorFaixaRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorFaixa
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorFaixa()
        {
        }
        
        public ConsultarNfsePorFaixa(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorFaixaResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorFaixaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorFaixaResponse()
        {
        }
        
        public ConsultarNfsePorFaixaResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface nfseChannel : XmlApiNfseGissInfra.NfseWSDL.nfse, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class nfseClient : System.ServiceModel.ClientBase<XmlApiNfseGissInfra.NfseWSDL.nfse>, XmlApiNfseGissInfra.NfseWSDL.nfse
    {
        
        public nfseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorRpsResponse> XmlApiNfseGissInfra.NfseWSDL.nfse.ConsultarNfsePorRpsAsync(XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorRps request)
        {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorRps inValue = new XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorRps();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((XmlApiNfseGissInfra.NfseWSDL.nfse)(this)).ConsultarNfsePorRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoTomadoResponse> XmlApiNfseGissInfra.NfseWSDL.nfse.ConsultarNfseServicoTomadoAsync(XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoTomado request)
        {
            return base.Channel.ConsultarNfseServicoTomadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoTomado inValue = new XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoTomado();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((XmlApiNfseGissInfra.NfseWSDL.nfse)(this)).ConsultarNfseServicoTomadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRpsResponse> XmlApiNfseGissInfra.NfseWSDL.nfse.RecepcionarLoteRpsAsync(XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRps request)
        {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRps inValue = new XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRps();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((XmlApiNfseGissInfra.NfseWSDL.nfse)(this)).RecepcionarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRpsSincronoResponse> XmlApiNfseGissInfra.NfseWSDL.nfse.RecepcionarLoteRpsSincronoAsync(XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRpsSincrono request)
        {
            return base.Channel.RecepcionarLoteRpsSincronoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRpsSincrono inValue = new XmlApiNfseGissInfra.NfseWSDL.RecepcionarLoteRpsSincrono();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((XmlApiNfseGissInfra.NfseWSDL.nfse)(this)).RecepcionarLoteRpsSincronoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoPrestadoResponse> XmlApiNfseGissInfra.NfseWSDL.nfse.ConsultarNfseServicoPrestadoAsync(XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoPrestado request)
        {
            return base.Channel.ConsultarNfseServicoPrestadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoPrestado inValue = new XmlApiNfseGissInfra.NfseWSDL.ConsultarNfseServicoPrestado();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((XmlApiNfseGissInfra.NfseWSDL.nfse)(this)).ConsultarNfseServicoPrestadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.CancelarNfseResponse> XmlApiNfseGissInfra.NfseWSDL.nfse.CancelarNfseAsync(XmlApiNfseGissInfra.NfseWSDL.CancelarNfse request)
        {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.CancelarNfseResponse> CancelarNfseAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            XmlApiNfseGissInfra.NfseWSDL.CancelarNfse inValue = new XmlApiNfseGissInfra.NfseWSDL.CancelarNfse();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((XmlApiNfseGissInfra.NfseWSDL.nfse)(this)).CancelarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarLoteRpsResponse> XmlApiNfseGissInfra.NfseWSDL.nfse.ConsultarLoteRpsAsync(XmlApiNfseGissInfra.NfseWSDL.ConsultarLoteRps request)
        {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            XmlApiNfseGissInfra.NfseWSDL.ConsultarLoteRps inValue = new XmlApiNfseGissInfra.NfseWSDL.ConsultarLoteRps();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((XmlApiNfseGissInfra.NfseWSDL.nfse)(this)).ConsultarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.GerarNfseResponse> XmlApiNfseGissInfra.NfseWSDL.nfse.GerarNfseAsync(XmlApiNfseGissInfra.NfseWSDL.GerarNfse request)
        {
            return base.Channel.GerarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.GerarNfseResponse> GerarNfseAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            XmlApiNfseGissInfra.NfseWSDL.GerarNfse inValue = new XmlApiNfseGissInfra.NfseWSDL.GerarNfse();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((XmlApiNfseGissInfra.NfseWSDL.nfse)(this)).GerarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.SubstituirNfseResponse> XmlApiNfseGissInfra.NfseWSDL.nfse.SubstituirNfseAsync(XmlApiNfseGissInfra.NfseWSDL.SubstituirNfse request)
        {
            return base.Channel.SubstituirNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.SubstituirNfseResponse> SubstituirNfseAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            XmlApiNfseGissInfra.NfseWSDL.SubstituirNfse inValue = new XmlApiNfseGissInfra.NfseWSDL.SubstituirNfse();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((XmlApiNfseGissInfra.NfseWSDL.nfse)(this)).SubstituirNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorFaixaResponse> XmlApiNfseGissInfra.NfseWSDL.nfse.ConsultarNfsePorFaixaAsync(XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorFaixa request)
        {
            return base.Channel.ConsultarNfsePorFaixaAsync(request);
        }
        
        public System.Threading.Tasks.Task<XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorFaixa inValue = new XmlApiNfseGissInfra.NfseWSDL.ConsultarNfsePorFaixa();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((XmlApiNfseGissInfra.NfseWSDL.nfse)(this)).ConsultarNfsePorFaixaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
